paths:
  raw_data: "./data/raw_data"
  prepared_data: "./data/prepared_data"
  archived_data: "./data/archived_data"
  exports: "./data/exports"   

logging:
  level: "${LOG_LEVEL:-INFO}"
  format: "${LOG_FORMAT:-json}"

usgs:
  monitoring_locations:
    base_url: "https://api.waterdata.usgs.gov/ogcapi/v0/collections/monitoring-locations/items"
    limit: 10000
    request_timeout: 10
    max_retries: 3
    timestamp_format: "%Y-%m-%dT%H:%M:%S"
    mode: "full"
    load_mode: "replace"s
    primary_key: ["id"]
    extra_params: {}
    transformations:
      uses_daylight_savings: yesno_to_bool
    critical_fields: ["id", "geometry"]
    id_field: "id"
    consistency_rules: ["geometry_requires_id"]

  daily_values:
    base_url: "https://api.waterdata.usgs.gov/ogcapi/v0/collections/daily/items"
    limit: 10000
    request_timeout: 10
    max_retries: 3
    timestamp_format: "%Y-%m-%dT%H:%M:%S"
    mode: "recent"
    recent_period: "P1M"
    load_mode: "upsert"
    primary_key: ["id"]
    extra_params:
      sites: "01491000"
      parameterCd: "00060"
    transformations:
      time: parse_datetime
      last_modified: parse_datetime
      geometry: flatten_geometry
    critical_fields: ["id", "geometry"]
    id_field: "id"
    consistency_rules: []

  parameter_codes:
    base_url: "https://api.waterdata.usgs.gov/ogcapi/v0/collections/parameter-codes/items"
    limit: 10000
    request_timeout: 10
    max_retries: 3
    timestamp_format: "%Y-%m-%dT%H:%M:%S"
    mode: "full"
    load_mode: "replace"
    primary_key: ["id"]
    extra_params: {}
    transformations:
      geometry: flatten_geometry
    critical_fields: ["id", "geometry"]
    id_field: "id"
    consistency_rules: []

db:
  host: "${DB_HOST:-localhost}"
  port: 5432
  database: "${DB_NAME:-monitoring}"
  user: "${DB_USER:-monitoring_user}"
  password: "${DB_PASSWORD:-password}"

views:
  unified_for_analysts:
    sql_file: sql/views/unified_for_gis.sql
  unified_for_gis:
    sql_file: sql/views/unified_for_analysts.sql

exports:  
  gis_export:
    view_name: "unified_gis_data"
    format: "gpkg"
  business_export:
    view_name: "unified_business_data"
    format: "csv"
