# config-test.yaml | overrides for testing environment

paths:
  raw_data: "./tests/_data/raw_data"
  prepared_data: "./tests/_data/prepared_data"
  archived_data: "./tests/_data/archived_data"
  exports: "./tests/_data/exports"

logging:
  level: "DEBUG"
  format: "json"

usgs:
  stations:
    base_url: "https://fake-api.com/api?"
    limit: 5
    request_timeout: 1
    max_retries: 1
    timestamp_format: "%Y-%m-%dT%H:%M:%S"
    mode: "test"
    load_mode: "replace"
    primary_key: ["id"]
    extra_params: {}
    transformations:
      geometry: flatten_geometry
    critical_fields: ["id"]
    id_field: "id"
    consistency_rules: []

db:
  host: "localhost"
  port: 5432
  database: "testdb"
  user: "test_user"
  password: "test_pass"

exports:
  test_export:
    view_name: "stations_test"
    format: "csv"
