# config.yaml | base config shared by all environments (production, development, testing)

paths:
  raw_data: "./data/raw_data"
  prepared_data: "./data/prepared_data"

# Look into CI/CD logging vs. Fluentbit
logging:
  level: "INFO"    # override via LOG_LEVEL in CI/CD
  format: "json"   # could be "plain" in dev

usgs:
  monitoring-locations:
    base_url: "https://api.waterdata.usgs.gov/ogcapi/v0/collections/monitoring-locations/items?f=json"
    limit: 10000
    request_timeout: 10
    max_retries: 3
    timestamp_format: "%Y%m%d_%H%M%S"

db:
  host: "localhost"   # override with DB_HOST in CI/CD
  port: 5432
  database: "monitoring"
