# config-test.yaml | overrides for testing environment

logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    json:
      class: pythonjsonlogger.jsonlogger.JsonFormatter
      format: '{"time": "%(asctime)s", "level": "%(levelname)s", "name": "%(name)s", "message": "%(message)s"}'

  handlers:
    console:
      class: logging.StreamHandler
      formatter: json
      level: DEBUG
      stream: ext://sys.stdout

  root:
    level: DEBUG
    handlers: [console]

usgs:
  monitoring_locations_url: "https://labs.waterdata.usgs.gov/api/collections/monitoring-locations/items?f=json"
  request_timeout: 5  # faster timeout for tests
  max_retries: 1

db:
  user: "test_user"
  password: "test_password"
  host: "localhost"
  port: 5432
  database: "test_monitoring"
