# config.yaml | base config shared by all environments (production, development, testing)

paths:
  raw_data: "./data/raw_data"
  prepared_data: "./data/prepared_data"

logging:
  level: "${LOG_LEVEL:-INFO}"
  format: "${LOG_FORMAT:-json}"

usgs:
  monitoring_locations:  # underscores for Python-friendly access
    base_url: "https://api.waterdata.usgs.gov/ogcapi/v0/collections/monitoring-locations/items?f=json"
    limit: 10000
    request_timeout: 10
    max_retries: 3
    timestamp_format: "%Y-%m-%dT%H:%M:%S"

db:
  host: "${DB_HOST:-localhost}"
  port: 5432
  database: "${DB_NAME:-monitoring}"
  user: "${DB_USER:-monitoring_user}"
  password: "${DB_PASSWORD:-password}"
