# config.yaml | base config shared by all environments (production, development, testing)

paths:
  raw_data: "./data/raw_data"
  prepared_data: "./data/prepared_data"

# Not yet implemented --------------------------
logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    json:
      class: pythonjsonlogger.jsonlogger.JsonFormatter
      format: '{"time": "%(asctime)s", "level": "%(levelname)s", "name": "%(name)s", "message": "%(message)s"}'

  handlers:
    console:
      class: logging.StreamHandler
      formatter: json
      level: INFO
      stream: ext://sys.stdout

  root:
    level: INFO
    handlers: [console]
# ----------------------------------------------

usgs:
  monitoring-locations:
    base_url: "https://api.waterdata.usgs.gov/ogcapi/v0/collections/monitoring-locations/items?f=json"
    limit: 10000
    request_timeout: 10
    max_retries: 3
    timestamp_format: "%Y%m%d_%H%M%S"

db:
  user: "cromanillos"
  password: "anypass"
  host: "localhost"
  port: 5432
  database: "monitoring"
